"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "./src"
"preserve_hierarchy": true
"base_url": "https://api.crowdin.com"

# Configure GitHub integration
"pull_request_title": "[i18n] updated translations from Crowdin"
"pull_request_labels": ["i18n", "crowdin"]

"files":
  [
    {
      "source": "content/docs/**/*.md",
      "translation": "content/docs/%two_letters_code%/**/%original_file_name%",
      "ignore": ["content/docs/ja/**/*", "content/docs/zh/**/*"],
      "update_option": "update_as_unapproved",
      "skip_untranslated_files": true,
    },
    {
      "source": "content/docs/**/*.mdx",
      "translation": "content/docs/%two_letters_code%/**/%original_file_name%",
      "ignore": ["content/docs/ja/**/*", "content/docs/zh/**/*"],
      "update_option": "update_as_unapproved",
      "skip_untranslated_files": true,
    },
    {
      "source": "content/i18n/en.json",
      "translation": "content/i18n/%two_letters_code%.json",
      "update_option": "update_as_unapproved",
      "skip_untranslated_files": true,
    },
  ]
